### ISSUE TITLE
Class 'Kunnu\Dropbox\DropboxApp' not found

### ISSUE THREAD

**Issue by wowaTYPO3** [froemken/dropbox#17]
Hi Frömmi,

I have installed the extension exactly as described in the tutorial, in TYPO3 11.5.6 with composer. After I inserted the access token and saved it in the record, the following exception appears. Also trying to edit the record afterwards only leads to the error message.
![2022-02-13_21-09-20](https://user-images.githubusercontent.com/343511/153773039-468675b5-1bb5-4a16-82e3-71e13ba58f6f.jpg)

**Comment by froemken** [comment]
Hello @wowaTYPO3 

thank you for your help. I found out that this Dropbox API has no support for PHP versions higher than 7.2. That's why I have switched to another Dropbox API now.

Problem should be solved now.

Stefan
