### ISSUE TITLE
Path in Typo3 of the "App"-drive/folder

### ISSUE THREAD

**Issue by GitCybers** [froemken/dropbox#19]
Hello,
I try to use the Dropbox extension for an ics-file which i want to import with the scheduler. I created a new record of type File Storage an on tab General I chose the name "Dropbox". In the filelist I can see the new drive "Dropbox" with all the files I copied inside. That means for me that the extension works...
But if I want to use the folder with the scheduler for the import of a file I don't know wich path I have to specify. I tried several variations, but nothing will work:
https://www.kgsfrankenforst.de/Dopbox/Schultermine/Schultermine.ics
Dropbox - /Schultermine/Schultermine.ics
Dropbox:/Schultermine/Schultermine.ics
4:/Schultermine/Schultermine.ics

Can you help me?
Thanks, Sascha

**Comment by froemken** [comment]
Hello @GitCybers 

thank you for this issue. I have tried to figure out the correct path. In filelist module you can navigate to your file and show file information. You will find a folder path and a filename. Combine them with the sys_file_storage UID to:

[sys_file_storage UID]:[folder]/[filename]

In my case I have tested it with simple TypoScript. Maybe you can try it that way first, too:

page.12 = IMAGE
page.12.file = 2:/Images/test-upload.jpg

I don't know your folder structure. Maybe that way is correct:

4:/Dropbox/Schultermine/Schultermine.ics

Nice greetings

Stefan
