### ISSUE TITLE
Refresh Token expires

### ISSUE THREAD

**Issue by tmay-px** [froemken/dropbox#29]
Typo3 Version: 11.5.27
EXT:dropbox Version: 4.3

The connection to the dropbox account expires after about 4 hours with error **Client error: `POST https://api.dropboxapi.com/2/users/get_current_account` resulted in a `401 Unauthorized` response: {"error":{".tag":"expired_access_token"},"error_summary":"expired_access_token/"}**

![Dropbox-Error](https://github.com/froemken/dropbox/assets/60698040/a857f7d3-54a4-4811-abc0-477aeaba6f28)

Is this a bug or am i missing some configuration in Typo3 or in the Dropbox Account?

Thanks in advance.

**Comment by mhuber84** [comment]
I can confirm this issue.

**Comment by pulponair** [comment]
Typo3 Version: 11.5.27
EXT:dropbox Version: 4.3
spatie/dropbox-api 1.22.0

Confirmed. 
Btw: why are you  are shiping another version of the dropbox api in Ressources/Private/PHP and Autoloading it?

**Comment by froemken** [comment]
Hello all together,

I have just released version 5.0.0 of my dropbox extension for TYPO3 11 and TYPO3 12.
Within this release you request just a refresh token from dropbox API and EXT:dropbox generates a 4 hour valid AccessToken for your requests. This token will be stored in sys_registry. If 4 hours are expired or a request throws a bad request EXT:dropbox will automatically update to the next valid 4 hour access token and tries last request automatically.

Have fun using the new version

Stefan
