### ISSUE TITLE
Not working in 6.2

### ISSUE THREAD

**Issue by dkoehl** [froemken/dropbox#3]
Hi,

you extension isnt´t working anymore.

Fatal error: Declaration of Tx_FalDropbox_Driver_Dropbox::getPublicUrl() must be compatible with TYPO3\CMS\Core\Resource\Driver\DriverInterface::getPublicUrl($identifier) in .../typo3conf/ext/fal_dropbox/Classes/Driver/Dropbox.php on line 38

**Comment by visay** [comment]
Hi,

You can try my patch where I submitted as pull request. https://github.com/froemken/fal_dropbox/pull/4

Let me know if that works for you.

Cheers,
Visay

**Comment by froemken** [comment]
getPublicUrl is extremely slow. In current version I don't use it anymore.
