### ISSUE TITLE
Image width and Height not updated in sys_file_metadata

### ISSUE THREAD

**Issue by dominiktome** [froemken/dropbox#5]
Hi,

i explored the following issue:
When i use fal_dropbox to integrate my Dropbox as filemount, every Meta-Info for sys_file is written correctly.
But to use for example the Image-Tools in tt_content or pages, there must be given "width" and "height" (wich are stored in sys_file_metadata). But these Params are not updated or written to Databse.

kind regards,

Dominik

**Comment by froemken** [comment]
That was a really heavy issue. Thank you for reporting. It costs me 6 hours to solve that. TYPO3 collects MetaData only on its own Local Driver. I found a hint in TYPO3 core that I have to create my own Extractor Service for other Drivers like Dropbox. But Dropbox does not deliver width and height over its API, so I have to download each image temporary and collect width and height. But that will not work automatically. This service only works with help of "MetaData scheduler Task" in TYPO3. So with each new file you have to start the scheduler or wait until next run. That's not my solution...that's the official solution of TYPO3.
