### ISSUE TITLE
Show & use images does not work in TYPO3 V10 (Core problem)

### ISSUE THREAD

**Issue by saschabrockel** [froemken/dropbox#9]
Hello. I just want to inform you that there is a bug in the core of TYPO3 in V10 that breaks the functionality while using a processed folder on local storage.

We are also developing an extension with FAL for a digital asset management software and used your extension as inspiration. And while using your extension we found this bug. We thought it was our fault because our TYPO3 instance is corrupt or our functions wrong but then we also tried the Google Drive extension and had the same experience. In TYPO3 V9 everything works fine. I also created an issue for the Google Drive extension whose developer told us that he experienced the same error. The exact error is described in it.

https://github.com/mabolek/google_drive_fal/issues/9

I created an issue on TYPO for this as well: https://forge.typo3.org/issues/93536

It would be nice if you could test it yourself for your extension and confirm the wrong behavior.

Thank you!

**Comment by froemken** [comment]
Hello @saschabrockel 

I have entered `1:/_processed_` as processed folder for my dropbox driver. The thumbnails are rendered correct, the images in FE are rendered correct, the path is correct, so I currently have a problem to reproduce your problem.

Maybe you have some more information for me which steps I have to do, do get this Exception.

Stefan

**Comment by saschabrockel** [comment]
Hello @froemken. We only did this for our master project at our university and stopped the development afterward. Maybe it's now fixed. But back then there was a bug in the core of TYPO3.

**Comment by froemken** [comment]
OK...I will close this issue for now. If you have any further information regarding this ticket, feel free to re-open this issue.

Thank you for your help.

Stefan
